# Generated by Django 3.0.5 on 2020-04-23 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('goal_kudos', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('C', 'complete'), ('A', 'active'), ('D', 'deleted')], default='A', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='goal',
            name='order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('not_until', models.DateTimeField(blank=True, null=True)),
                ('order_within_project', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('C', 'complete'), ('A', 'active'), ('D', 'deleted')], default='A', max_length=1)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks', to='todoapp.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_projects', to='todoapp.Goal'),
        ),
    ]
