# Generated by Django 3.0.5 on 2020-04-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_auto_20200422_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
